### ISSUE TITLE
Missing interface for CDVWKInAppBrowserViewController and undeclared _settings

### ISSUE THREAD

**Issue by yyorick** [apache/cordova-plugin-inappbrowser#720]
# Bug Report

### What is expected to happen?
Recently upgraded the ios platform from 5.x.x to 6.0.0 to deal with deprecated UIWebView issues related to the appstore.

with ios@6.0.0, the application will not build with the InAppBrowser plugin (3.2.0) and (4.0.0-dev).

### What does actually happen?
in CDKVWKInAppBrowser.m, line 201:
`    if (self.inAppBrowserViewController == nil) {
        self.inAppBrowserViewController = [[CDVWKInAppBrowserViewController alloc] initWithBrowserOptions: browserOptions andSettings:self.commandDelegate.settings];
        self.inAppBrowserViewController.navigationDelegate = self;
        
        if ([self.viewController conformsToProtocol:@protocol(CDVScreenOrientationDelegate)]) {
            self.inAppBrowserViewController.orientationDelegate = (UIViewController <CDVScreenOrientationDelegate>*)self.viewController;
        }
    }`

> No visible @interface for 'CDVWKInAppBrowserViewController' declares the selector 'initWithBrowserOptions:andSettings:'

additionally, line 703:
`- (id)initWithBrowserOptions: (CDVInAppBrowserOptions*) browserOptions andSettings:(NSDictionary *)settings
{
    self = [super init];
    if (self != nil) {
        _browserOptions = browserOptions;
        _settings = settings;
        self.webViewUIDelegate = [[CDVWKInAppBrowserUIDelegate alloc] initWithTitle:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"]];
        [self.webViewUIDelegate setViewController:self];
        
        [self createViews];
    }
    
    return self;
}`

and line 906:
`    return [_settings objectForKey:[key lowercaseString]];`

> Use of undeclared identifier '_settings'

## Information
Building the app without InAppBrowser is successful, but the ability to navigate the pages using the iphone touchscreen is lost.

### Version information

Cordova:

> Installed platforms:
>   android 8.1.0
>   ios 6.0.0
> 
> cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
> cordova-plugin-blurred-snapshot 0.1.3 "cordova-plugin-blurred-snapshot"
> cordova-plugin-brightness 0.1.5 "Brightness"
> cordova-plugin-dialogs 2.0.2 "Notification"
> cordova-plugin-inappbrowser 4.0.0-dev "InAppBrowser"
> cordova-plugin-native-spinner 1.1.3 "Native Spinner"
> cordova-plugin-qrscanner 3.0.1 "QRScanner"
> cordova-plugin-splashscreen 5.0.4 "Splashscreen"
> cordova-plugin-statusbar 2.4.3 "StatusBar"
> cordova-plugin-whitelist 1.3.4 "Whitelist"
> cordova-support-google-services 1.3.2 "cordova-support-google-services"
> phonegap-plugin-multidex 1.0.0 "Multidex"
> phonegap-plugin-push 2.3.0 "PushPlugin"

Xcode:

> Xcode 11.5
> Build version 11E608c

Angular:

> Angular CLI: 9.0.3
> Node: 12.16.1
> OS: darwin x64

Angular: 

@angular-devkit/architect    0.900.3
@angular-devkit/core         9.0.3
@angular-devkit/schematics   9.0.3
@schematics/angular          9.0.3
@schematics/update           0.900.3
rxjs                         6.5.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
I can't reproduce on 4.0.0 final, so you might be using an old 4.0.0-dev where it wasn't fixed yet
