### ISSUE TITLE
'Cordova/CDVUserAgentUtil.h' file not found on cordova-ios@6 

### ISSUE THREAD

**Issue by eun-choi** [apache/cordova-plugin-inappbrowser#709]
1) cordova plugin add cordova-plugin-inappbrowser@3.2
2) cordova platform add ios@5.1.1
3) xcode build pass.

4) cordova platform rm ios
5) cordova platform add ios@6
6) xcode build failed.
 - error file: CDVWKInAppBrowser.m 
 - error line: 27
 - error msg: 'Cordova/CDVUserAgentUtil.h' file not found

it seems to be related https://github.com/apache/cordova-ios/pull/801

**Comment by erisu** [comment]
The current release of IAB does not and will not work with Cordova iOS 6.0.0.

This is expected as the `CDVUserAgentUtil` was apart of the `UIWebView`. The next major release of IAB removes `CDVUserAgentUtil`.

https://github.com/apache/cordova-plugin-inappbrowser/pull/635

**Comment by markamccorkle** [comment]
@erisu Any ETA on the IAB release? This is a breaking change for anyone updating to `cordova-ios:6.0.0`

**Comment by AdriVanHoudt** [comment]
hey @erisu 
Thanks for your work on cordova ✨ 
This error also caught me off guard and it took me a while to find what was going on.
I understand that releases depend on voluntary work so hard dates etc are hard but since IAB is so widely used it might be worth just adding a note on the release notes (on the blog). If this is something I can do (pr wise) I would love to help!

**Comment by timbru31** [comment]
All relevant development (not support!) communication is over at our mailing lists (dev@cordova.apache.org): https://lists.apache.org/thread.html/r4355de14684f1fb0c70a90f94cf76c6ee2645fc82a5a34af1e41c9c9%40%3Cdev.cordova.apache.org%3E

Feel free to join the list and participate in the voting and testing once Niklas made the [VOTE] thread.

**Comment by prodrammer** [comment]
Was this intended to be fixed in cordova-plugin-inappbrowser@4.0.0? I am running cordova-ios@6.1.0 and cordova-plugin-inappbrowser@4.0.0.

When I try to build, I get the following error.
```
Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m:27:9: fatal error: 
      'Cordova/CDVUserAgentUtil.h' file not found
#import <Cordova/CDVUserAgentUtil.h>
```

Any ideas? I need to publish my app :-).

**Comment by prodrammer** [comment]
I didn't understand that you can add specific versions of ios in the platform command. Running `cordova platform add ios` installs the latest version of cordova-ios which is currently 6.1.0 which **causes the build to fail with the latest release of `cordova-plugin-inappbrowser`**.

The workaround is:

```
cordova platform rm ios
cordova platform add ios@5.1.1
```

@timbru31 Are you aware of this issue?

**Comment by timbru31** [comment]
There is no issue with installing it both latest versions. You probably have a dirty platforms or plugins folder.

**Comment by prodrammer** [comment]
@timbru31 I have a reset script that removes node_modules and platforms and reinstalls. I failed to include removal of the plugins folder. I updated my script and re-ran. **It worked! Thanks!** However, I didn't "dirty" the plugins folder. Maybe that's an issue that should be looked into?

**Comment by breautek** [comment]
> @timbru31 I have a reset script that removes node_modules and platforms and then reinstalls. I failed to include removal of the plugins folder. I updated my script and re-ran. **It worked! Thanks!** However, I didn't "dirty" the plugins folder. Maybe that's an issue that should be looked into?

tbh, I'm not exactly sure on the purpose of the `plugins` folder, I believe it's an artefact of pre-npm days where Apache Cordova had its own plugin repository. I think all code responsible for loading/copying plugins to the plugin folder can be removed, but this is really a discussion that should be placed in the dev mailing.

**Comment by prodrammer** [comment]
@breautek Message sent. Thanks!

**Comment by jammind** [comment]
@erisu Thanks for your amazing work. As Apple's UIWebView deadline is approaching, we really need the plugin that is compatible with Cordova iOS 6. Is there a schedule for the upgrade?
