### PR TITLE
feat: Add compile-time decision for disabling UIWebView

### LINKED ISSUE #583: iOS - build fails if using "WKWebViewOnly" preference
# Bug Report

### What is expected to happen?
`cordova build ios` Build success

### What does actually happen?
```
$ cordova build ios
...
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/foo/Library/Developer/Xcode/DerivedData/HelloWorld-euwessldwjxdluatamnrumldwksu/Build/Intermediates.noindex/HelloWorld.build/Debug-iphonesimulator/HelloWorld.build/Objects-normal/x86_64/CDVUIInAppBrowser.o /Users/foo/dev/hello/platforms/ios/HelloWorld/Plugins/cordova-plugin-inappbrowser/CDVUIInAppBrowser.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
```

## Information

Since [cordova-ios@5.1.0](https://cordova.apache.org/announcements/2019/11/25/cordova-ios-release-5.1.0.html) and following https://github.com/apache/cordova-ios/pull/715
If you add "WKWebViewOnly" preference, then `cordova build` fails on using cordova-plugin-inappbrowser

(ping https://github.com/apache/cordova-plugin-inappbrowser/pull/535 & https://github.com/apache/cordova-plugin-inappbrowser/issues/532)

### Command or Code

```
cordova create hello com.example.hello HelloWorld
cd hello
cordova platform add ios
cordova plugin add cordova-plugin-inappbrowser
<<add "WKWebViewOnly" preference into config.xml>>
cordova build ios
```

### Version information

Cordova CLI *9.0.0*
Cordova Platform *iOS* (5.1.0)
Cordova Plugin *cordova-plugin-inappbrowser* (3.1.0)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by beevelop**
This PR fixes #583.

With the introduction of the `WK_WEB_VIEW_ONLY` flag, references to UIWebView are removed from the source. I tried to adapt the same changes from https://github.com/apache/cordova-ios/pull/715 to this project.

### CODE REVIEW

**Comment by ath0mas** [comment]
Tried your fork, with and without "WKWebViewOnly" preference, and it's OK for me
💯 
> ** BUILD SUCCEEDED **

@beevelop you didn't change references in `plugin.xml` as you suggested? and indeed I think it would prevent plugin to install or build correctly when *not* using "WKWebViewOnly" preference?

**Comment by beevelop** [comment]
Thank you for the feedback.

Yeah, modifying the `plugin.xml` is not necessary when using the compile-time approach. This way, we also stay backwards compatible.

**Comment by ath0mas** [comment]
Please, any update from team to review/merge this? And possible release 😇 ?

**Comment by mjamal4u** [comment]
> Please, any update from team to review/merge this? And possible release 😇 ?

We are also in same pool. Would be great help if we can have early release :)

**Comment by bbialas** [comment]
@beevelop any chances to merge this one soon?

**Comment by beevelop** [comment]
@bbialas Unfortunately, I'm not in charge.
Maybe @breautek, @janpio or @NiklasMerz can help with that?

**Comment by NiklasMerz** [comment]
I am not an Apache Commiter, too. Since I still got no warning from Apple after uploading an app I did not test the flag, yet.

@dpa99c You are an expert for in app browser.

**Comment by breautek** [comment]
Sorry @beevelop I generally stay away from iOS pull requests because I don't have personal apple hardware to use for testing, and I'm not very experienced in objective-c either.

But i can say that PRs won't get merged into until all checks passes. Currently it is failing for what appears to be an issue with the tests getting a webview context.

```
No webview context. Retries remaining: 2
cordova-paramedic: Tests failed to complete; ending session. The error is:
Error: [context("WEBVIEW_5906.1")] Error response status: 21, Timeout - An operation did not complete before its timeout expired. Selenium error: Automation Server Error -- Selenium didn't complete your last command on time.
For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
```
https://travis-ci.org/apache/cordova-plugin-inappbrowser/jobs/617811060?utm_medium=notification&utm_source=github_status

My educated guess tells me this is because the tests are probably trying to run in a cordova-ios environment without a wkwebview plugin installed. But not 100% sure if this is the case.

**Comment by beevelop** [comment]
@breautek The builds are failing due to an error in the pipelines. They are not exactly related to the changes in this PR. See https://github.com/apache/cordova-plugin-inappbrowser/issues/491 or compare to https://github.com/apache/cordova-plugin-inappbrowser/pull/528 (CI checks also failed). Not quite sure, on how to proceed there.

**Comment by ath0mas** [comment]
@breautek how to/can we rerequest check suite?

**Comment by Kepro** [comment]
c'mon guys! you can do it! cannot wait for fix :) like really cannot wait :D

**Comment by Kepro** [comment]
hey, I tried these changes locally but now I got `CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.`

**Comment by ath0mas** [comment]
@Kepro more context or log or a minimal reproducible example is needed to understand your problem

**Comment by Kepro** [comment]
@ath0mas hi there, sorry!
"cordova-ios": "5.1.1" (latest)
cordova-plugin-inappbrowser: 3.1.0 (latest)
```
2019-12-20 09:36:38.164820+0100 XXX532:103173] Apache Cordova native platform version 5.1.1 is starting.
2019-12-20 09:36:38.167505+0100 XXX[532:103173] Multi-tasking -> Device: YES, App: YES
2019-12-20 09:36:38.184551+0100 XXX[532:103173] [CDVTimer][console] 0.204921ms
2019-12-20 09:36:38.185113+0100 XXX[532:103173] [CDVTimer][handleopenurl] 0.293016ms
2019-12-20 09:36:38.193607+0100 XXX[532:103173] [CDVTimer][intentandnavigationfilter] 8.319974ms
2019-12-20 09:36:38.194196+0100 XXX[532:103173] [CDVTimer][gesturehandler] 0.292063ms
2019-12-20 09:36:38.227851+0100 XXX[532:103173] [CDVTimer][file] 33.380032ms
2019-12-20 09:36:38.229283+0100 XXX[532:103173] [CDVTimer][inappbrowser] 1.068950ms
2019-12-20 09:36:38.229725+0100 XXX[532:103173] CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.
2019-12-20 09:36:38.229895+0100 XXX[532:103173] [CDVTimer][uiinappbrowser] 0.292897ms
2019-12-20 09:36:38.230252+0100 XXX[532:103173] [CDVTimer][wkinappbrowser] 0.262022ms
2019-12-20 09:36:38.246181+0100 XXX[532:103173] [CDVTimer][splashscreen] 15.802026ms
2019-12-20 09:36:38.262580+0100 XXX[532:103173] [CDVTimer][statusbar] 16.147971ms
2019-12-20 09:36:38.264041+0100 XXX[532:103173] [CDVTimer][localstorage] 1.145959ms
2019-12-20 09:36:38.264271+0100 XXX[532:103173] [CDVTimer][TotalPluginStartup] 80.597043ms
```

**Comment by Kepro** [comment]
okay, it now complains about it but it's working together with `cordova-plugin-wkwebview-engine` in config.xml
```
			<!-- Cordova WKWebView engine  -->
			<preference name="WKWebViewOnly" value="true" />
			<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
			<feature name="CDVWKWebViewEngine">
				<param name="ios-package" value="CDVWKWebViewEngine" />
			</feature>
```
debug
```
2019-12-20 12:19:12.953981+0100 xxx[874:136760] Using WKWebView
2019-12-20 12:19:12.955626+0100 xxx874:136760] [CDVTimer][console] 0.215054ms
2019-12-20 12:19:12.956149+0100 xxx[874:136760] [CDVTimer][handleopenurl] 0.254035ms
2019-12-20 12:19:12.964714+0100 xxx[874:136760] [CDVTimer][intentandnavigationfilter] 8.396983ms
2019-12-20 12:19:12.965167+0100 xxx[874:136760] [CDVTimer][gesturehandler] 0.229955ms
2019-12-20 12:19:12.970830+0100 xxx[874:136760] [CDVTimer][file] 5.452037ms
2019-12-20 12:19:12.971308+0100 xxx[874:136760] [CDVTimer][inappbrowser] 0.223994ms
2019-12-20 12:19:12.971499+0100 xxx[874:136760] CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.
2019-12-20 12:19:12.971592+0100 xxx[874:136760] [CDVTimer][uiinappbrowser] 0.149012ms
2019-12-20 12:19:12.971875+0100 xxx[874:136760] [CDVTimer][wkinappbrowser] 0.194073ms
```

**Comment by ath0mas** [comment]
Not much time to look at it these days so if anyone has a feedback for @Kepro feel free :)

**Comment by chukwumaokere** [comment]
Hi, Sorry to be "that guy" but I'm fairly new at this. I have encountered this issue and I want to use the PR version that has this fix for a client production build I'm working on, but I'm not sure how to specify in some file to pull the versions from this PR instead of the regular dependency that's lacking this fix. Any tips? 

Thanks in advance!

**Comment by breautek** [comment]
> Hi, Sorry to be "that guy" but I'm fairly new at this. I have encountered this issue and I want to use the PR version that has this fix for a client production build I'm working on, but I'm not sure how to specify in some file to pull the version from this PR instead of the regular dependency that's lacking this fix. Any tips?
> 
> Thanks in advance!

No problem, there is a first time for everything! I'll provide a step-by-step instructions below.

1. Fork the `inappbrowser` plugin to your own account using the "Fork" button on github, on the top-right of the page.
2. Run `git clone <your fork repo url>`
3. Now we need to add the repo we want to merge in form as a new remote. In this case, from neohelden's github. So run `git remote add neohelden https://github.com/neohelden/cordova-plugin-inappbrowser.git`
4. Now we can fetch neohelden's changesets. Run `git fetch neohelden`
5. Because neohelden made their changes in their master branch, we can merge their master branch into your own fork. Run `git merge neohelden/master`
6. Now push the changes your own repo. Run `git push`
7. Finally, you can install your version of the plugin by using, `cordova plugin add https://yourgithubforkurl`

Alternatively, you can just install neohelden's copy by using `cordova plugin add https://github.com/neohelden/cordova-plugin-inappbrowser.git` which might be a good idea just to test it out before spending the time preparing your own fork, but you're at the mercy of a third-party making unexpected changes, or even deleting the fork/repo altogether, so it's just safer to create your own fork to ensure unexpected changes.

**Comment by chukwumaokere** [comment]
Worked perfectly. You've been a tremendous help, @breautek 
Cant thank you enough!

**Comment by ath0mas** [comment]
@beevelop were you able to look at the log @Kepro gets at runtime?
`CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.`

**Comment by rajashekaranugu** [comment]
Hello All, do we have any update regarding this issue?. Thanks in advance

**Comment by NiklasMerz** [comment]
We are planning a minor release with this merged soon. But this issue
still needs some reviews and testing.

**Comment by Kepro** [comment]
@NiklasMerz will you create also a new release, please? :)

**Comment by NiklasMerz** [comment]
I think we can merge this after getting another positive review.

We are tracking the next release [here](https://github.com/apache/cordova-plugin-inappbrowser/milestone/2). As soon as those PRs are merged, the release process should start.

File: src/ios/CDVInAppBrowser.m [hunk 1]
```diff
@@ -49,86 +51,122 @@ - (void)open:(CDVInvokedUrlCommand*)command
         return;
     }
     self.usewkwebview = browserOptions.usewkwebview;
-    if(self.usewkwebview){
-        [[CDVWKInAppBrowser getInstance] open:command];
-    }else{
-        [[CDVUIInAppBrowser getInstance] open:command];
-    }
+    #if WK_WEB_VIEW_ONLY
```
Comment (brodybits) [inline src/ios/CDVInAppBrowser.m]: I personally find the number of these conditional blocks to be quite a bit ugly. I suspect there should be some clean way to abstract out `[CDVWKInAppBrowser getInstance]` vs `[CDVUIInAppBrowser getInstance]`.

Comment (NiklasMerz) [reply src/ios/CDVInAppBrowser.m]: I am not a fan of this build flag, too. It is kind of ugly and hard to get while reading this code (for non-objective-c devs) but I think it is great for an interim solution until #535 gets released in a **major** release hopefully soon.

**Comment by rajashekaranugu** [comment]
Hi @erisu and all. How long will it take to publish this change and merge

**Comment by NiklasMerz** [comment]
I am planning to merge this and start the release process in a few hours.

I hope the release is ready in the next days.

**Comment by rajashekaranugu** [comment]
> I am planning to merge this and start the release process in a few hours. I hope the release is ready in the next days. Am 3. Jan. 2020, 23:25, um 23:25, Rajashekar Reddy <notifications@github.com> schrieb:
> […](#)
> Hi @erisu and all. How long will it take to publish this change and merge -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#584 (comment)](https://github.com/apache/cordova-plugin-inappbrowser/pull/584#issuecomment-570716651)

Thanks for the quick response @NiklasMerz

**Comment by beevelop** [comment]
Thank you @NiklasMerz

**Comment by NiklasMerz** [comment]
Thank you @beevelop for your contribution and everyone else here for testing and reviewing this.

The release is prepared and currently at the VOTE step. We appreciate votes from everybody, if you would like to test this release candidate. If the vote passes this is in the next official release in a few days.

See the mailing list here: https://lists.apache.org/thread.html/948904caf4252fc7e653cbf1adf70160b2ccbe98658e075fc89aaea1%40%3Cdev.cordova.apache.org%3E

**Comment by DRK1004** [comment]
Its great that new version of this plugin is released, as it was much awaited thing. 
But while taking a look on the changes, I observed below change, which seems incorrect to me.

```
- (void)injectScriptFile:(CDVInvokedUrlCommand*)command
{
    #if WK_WEB_VIEW_ONLY
      [[CDVWKInAppBrowser getInstance] injectScriptCode:command];
    #else
      if(self.usewkwebview){
          [[CDVWKInAppBrowser getInstance] injectScriptCode:command];
      }else{
          [[CDVUIInAppBrowser getInstance] injectScriptCode:command];
      }
    #endif
}
```

 Let me know if below code is fine or its a copy paste mistake.

**Comment by NiklasMerz** [comment]
@DRK1004 Good spot! That issue went through. I will fix it now and start the release again.

**Comment by NiklasMerz** [comment]
The release process is started again. We also invite people who are not committers or PMC members to vote on releases to catch issues like this one and produce better releases. Feel free to try voting yourself: https://github.com/apache/cordova-coho/blob/master/docs/release-voting.md#release-voting-guidelines

You can vote by replying to this Email and get updates on the release via the Cordova mailing list. https://lists.apache.org/thread.html/r8e10307d2ce0efe1e881db0b5f6c714cb162ce96a59655b1c9edd4a6%40%3Cdev.cordova.apache.org%3E

**Comment by irene-pc** [comment]
@NiklasMerz I can't not update InAppBrowser plugin to version 3.2.0. Is it due to relased process started again?

**Comment by timbru31** [comment]
@irene-pc - yes, the new release is still in the [voting phase](https://github.com/apache/cordova-coho/blob/master/docs/plugins-release-process.md#voting-and-release) and the 48 hours have not yet passed.

See Niklas' second link for the current voting situation (and feel free to test the release and add a non-binding vote)

**Comment by irene-pc** [comment]
> @irene-pc - yes, the new release is still in the [voting phase](https://github.com/apache/cordova-coho/blob/master/docs/plugins-release-process.md#voting-and-release) and the 48 hours have not yet passed.
> 
> See Niklas' second link for the current voting situation (and feel free to test the release and add a non-binding vote)

Thank you so much for the information @timbru31 I'm newbie here and I don't know very well how does updates work and when are they available.

**Comment by Kepro** [comment]
if I use "master" branch and I will use <preference name="WKWebViewOnly" value="true" />
then I got 
`2020-01-08 17:01:09.517925+0100 InSight Assess[2441:1535723] [CDVTimer][inappbrowser] 0.198960ms
2020-01-08 17:01:09.518268+0100 InSight Assess[2441:1535723] CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.
2020-01-08 17:01:09.518376+0100 InSight Assess[2441:1535723] [CDVTimer][uiinappbrowser] 0.271916ms
2020-01-08 17:01:09.518652+0100 InSight Assess[2441:1535723] [CDVTimer][wkinappbrowser] 0.187993ms`

nobody else got this issue?

**Comment by brodybits** [comment]
In case of issues with the master branch or upcoming release from npm then please raise a new issue with a [minimal, reproducible example][minimal-reproducible-example]. We do not have extra resources to support discussions in merged PRs or closed issues.

[minimal-reproducible-example]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by irene-pc** [comment]
Does anyone know when version 3.2.0 will be available in npm?

**Comment by NiklasMerz** [comment]
This has been answered many times. Please read above. The release is in progress.

Please be patient. Asking won't make it faster. Releases are available when they are done.

**Comment by brodybits** [comment]
FYI we have finished voting on the release and expect to publish it very soon. Please feel free to ping me personally (don't ping any other individuals) in case it really does take too long.

Release discussions and voting threads generally happen on the mailing list. It is also fine to contact us by Slack in case of any questions. Links to find the mailing list and Slack channel are in the footer of cordova.io which redirects to: cordova.apache.org

In general, we would appreciate a reasonable amount of patience since Apache Cordova is maintained by a bunch of generally overworked volunteers. But please do feel free to follow up with us in case of any unreasonable delays.

**Comment by mjamal4u** [comment]
For all incredible contributors on this issue. This release means a lot for our Apps. Thank you !!!

**Comment by NiklasMerz** [comment]
Thank you all here for your patience and testing this PR. I am proud to announce that **version 3.2.0 is now available on NPM**. The release blog post will be on cordova.apache.org very soon.

**Comment by irene-pc** [comment]
Thank you so much to all of you. 

@brodybits thank you so much for your response. I am newbie in the whole process of launching a new version :)

**Comment by NiklasMerz** [comment]
> This has been answered many times. Please read above. The release is in progress. Please be patient. Asking won't make it faster. Releases are available when they are done. 

@irene-pc Revisiting this comment now, I realised that it could sound rude. That was not my intent and I am sorry about that.

I am new member of the PMC and I am still figuring out how to work on releases. Chris and Tim did a great job to explain how the Cordova community works. I would advise you to join the mailing list to get the latest news.

Thank you all in this thread very much for supporting my first release.

**Comment by ath0mas** [comment]
Released 3.2.0 works perfect, thanks you to all contributors 😍 
And congrats @NiklasMerz for your first release! :)

**Comment by irene-pc** [comment]
Hallo @NiklasMerz Nothing happens. It is normal. It's your first release and maybe it is all new for you. You did a great job. My main concern was Apple email and with this update I don't receive it. Thank you so much :+1: 
I think it is a great idea to join the mailing list. How can I do that?

**Comment by NiklasMerz** [comment]
@irene-pc You can find everything here https://cordova.apache.org/contact/

**Comment by irene-pc** [comment]
@NiklasMerz Thank you

**Comment by jtibbles** [comment]
Thanks @NiklasMerz . Quick question - does the plugin need the platform ios5.1.1 to work or is 5.1.0 sufficient?

**Comment by NiklasMerz** [comment]
This should work with 5.1.0 where `WKWebViewOnly` was introduced. But version 5.1.1 is just a patch version with just a few fixes you should prefer .

**Comment by erisu** [comment]
@jtibbles @NiklasMerz I would recommend using Cordova-iOS 5.1.1.

In 5.1.0, yes the `WKWebViewOnly` flag was introduced but there was a bug that caused the `cordova platform add ios` command to fail when the flag was set in `config.xml` before adding the platform. For the issue ticket you, refer to https://github.com/apache/cordova-ios/issues/725

This bug is fixed. The fix is in Cordova-iOS 5.1.1.

**Comment by minhngl** [comment]
@NiklasMerz @erisu I got the following errors and build fails while set "WKWebViewOnly" preference = true.  Is this the bugs of InAppBrowser or I did something wrong?

Plugins/cordova-plugin-inappbrowser/CDVUIInAppBrowser.m:601:56: error: assignment to readonly property
    self.inAppBrowserViewController.navigationDelegate = nil;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~
Plugins/cordova-plugin-inappbrowser/CDVUIInAppBrowser.m:631:30: error: use of undeclared identifier 'CDVUIWebViewDelegate'
        _webViewDelegate = [[CDVUIWebViewDelegate alloc] initWithDelegate:self];
~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Plugins/cordova-plugin-inappbrowser/CDVUIInAppBrowser.m:672:18: error: assignment to readonly property
    self.spinner = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Version information
Cordova CLI 9.0.0
Cordova Platform iOS (5.1.1)
Cordova Plugin cordova-plugin-inappbrowser (3.2.0)

**Comment by timbru31** [comment]
Please seek support on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

**Comment by PigeonPanet** [comment]
Hi everyone, 
I have the same problem as here: https://github.com/apache/cordova-plugin-inappbrowser/pull/584#issuecomment-57213664 . 

package.json:

    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-ios": "^5.1.1",

config. xml: 
  <preference name="WKWebViewOnly" value="true" />

My error: CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.

**Comment by Yelles** [comment]
> Hi everyone,
> I have the same problem as here: [#584 (comment)](https://github.com/apache/cordova-plugin-inappbrowser/pull/584#issuecomment-57213664) .
> 
> package.json:
> 
> ```
> "cordova-plugin-ionic-webview": "^4.2.1",
> "cordova-plugin-inappbrowser": "^3.2.0",
> "cordova-ios": "^5.1.1",
> ```
> 
> config. xml:
> preference name="WKWebViewOnly" value="true"
> 
> My error: CDVPlugin class CDVUIInAppBrowser (pluginName: uiinappbrowser) does not exist.

same for me, any solution ?

**Comment by NiklasMerz** [comment]
Please try deleting the iOS platform and add it again. That should clean stuff up that got lost in the update. Make sure you are using the latest versions of those plugins and platforms.

Locking this because pull requests and issues are not for questions. As Tim said please go to Stack Overflow or Slack.
